name: flutter_liquid_glass
description: A comprehensive Flutter package that brings Apple's Liquid Glass design language to Flutter apps with extensive customization options.
version: 1.0.0
homepage: https://github.com/CanArslanDev/flutter_liquid_glass
repository: https://github.com/CanArslanDev/flutter_liquid_glass
issue_tracker: https://github.com/CanArslanDev/flutter_liquid_glass/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0

flutter:
  # No assets required